camera:
  color_width: 640
  color_height: 480
  color_fps: 5
  enable_depth: true
  depth_width: 640
  depth_height: 480
  depth_fps: 5
  enable_ir: false

thermal_camera:
  device: /dev/video0
  width: 256
  height: 392
  fps: 25
  pixel_format: YUYV
  output_encoding: yuv422_yuy2
  frame_id: thermal_camera_frame
