human_box_tracker_node:
  ros__parameters:
    model_name: efficientdet_lite0_person_boxes
    model_path: /home/andrew/ros2-initiator-drone/models/efficientdet_lite0.tflite
    image_topic: /camera/color/image_raw
    boxes_topic: /human_pose/keypoints
    person_detected_topic: /human_pose/person_detected
    debug_image_topic: /human_pose/debug_image
    confidence_threshold: 0.35
    max_detections: 8
    crop_left_px: 29
    crop_right_px: 29
    crop_top_px: 0
    crop_bottom_px: 0
    track_iou_threshold: 0.3
    max_track_missed_frames: 5
    max_inference_fps: 2.0
    publish_debug_image: true
    allow_missing_model_debug_stream: true
